tmax-cloud/template-operator

- controllers/templateinstance_controller.go
- instance parameter 없을 경우, template에서 정의한 default parameter value 쓸 수 있도록 로직 수정
> [mod] add default parameter logic in instance

- docs/template.yaml
- 서비스 카탈로그 서비스 테스트 할수 있도록 swagger 문서 추가 (for UI 등.)
> [feat] add swagger

- README.md
- api/v1/catalogserviceclaim_types.go
- config/crd/bases/tmax.io_catalogserviceclaims.yaml
- config/samples/example-catalogserviceclaim.yaml
- config/samples/nginx-catalogserviceclaim.yaml
- controllers/catalogserviceclaim_controller.go
- docs/template.yaml
- claim 로직 변경
- namespaced scope로 변경
- clustertemplate owner reference 제거
- handled status 추가 (reject, approve 이후 reconcile 막기 위함)
- swagger api 문서, README 업데이트
> [mod] catalogserviceclaim logic

- .github/workflows/main.yaml
- Makefile
- config/crd/bases/tmax.io_catalogserviceclaims.yaml
- config/crd/bases/tmax.io_clustertemplates.yaml
- config/crd/bases/tmax.io_templateinstances.yaml
- config/crd/bases/tmax.io_templates.yaml
> [feat] add workflow

- .github/workflows/main.yaml
- controllers/clustertemplate_controller_test.go
[feat] Add test code for clustertemplate controller
[mod] Update workflow yaml
> [feat] Add clustertemplate_controller test

- controllers/clustertemplateclaim_controller.go
- Reflect admin's reject reason to clustertemplateclaim cr
> [feat] Reflect admin reject reason to claim cr

- controllers/clustertemplate_controller.go
- controllers/templateinstance_controller.go
- controllers/templateinstance_controller_test.go
- Assign envValue "REPLICAS" as sting type and check if it works properly (automatically convert to int type)
> [test] update parameter valuetype missmatch test

- controllers/clustertemplate_controller.go
- controllers/template_controller.go
Fill the templatespec(both Template & ClusterTemplate) field with default values
> [mod] Fill the templatespec field with default values

- api/v1/template_types.go
- config/crd/bases/tmax.io_clustertemplates.yaml
- config/crd/bases/tmax.io_templateinstances.yaml
- config/crd/bases/tmax.io_templates.yaml
- ShortDescription : omitempty -> Not omitempty
- Objects : omitempty -> Not omitempty 
- UrlDescription : Not omitempty -> omitempty
Applied changes to CRD bases yaml files (make manifests)
> [mod] arranged templateSpec field json tag 'omitempty'

- api/v1/template_types.go
- config/crd/bases/tmax.io_clustertemplates.yaml
- config/crd/bases/tmax.io_templateinstances.yaml
- config/crd/bases/tmax.io_templates.yaml
update shortDescription field to omitempty
> [mod] update shortDescription field to omitempty

- controllers/templateinstance_controller.go
- enable template Instance update by deleting status checking logic
> [feat] enable templateinstance update by deleting status checking

- controllers/templateinstance_controller.go
- Number Type of parameter replacement bug fixed
> [fix] numberType parameter replacement bug fix

- controllers/clustertemplate_controller.go
- controllers/template_controller.go
- Removed template status check logic in order to set templateSpec default values whenever it updated
> [feat] removed template status check

- api/v1/template_types.go
- config/crd/bases/tmax.io_clustertemplates.yaml
- config/crd/bases/tmax.io_templateinstances.yaml
- config/crd/bases/tmax.io_templates.yaml
- controllers/templateinstance_controller.go
- controllers/templateinstance_controller_test.go
- Add regex field in Parameter spec
- Add regex validation of parameter value
> [feat] add regex validation of parameter

- .gitignore
- controllers/clustertemplate_controller.go
- controllers/template_controller.go
- internal/resolver/template_resolver.go
- add component to handle template modifying logic
- move template modifying logic to resolver component
> Refactor template/cluster-template controller

- controllers/clustertemplate_controller.go
- controllers/clustertemplate_controller_test.go
- controllers/clustertemplateclaim_controller.go
- controllers/template_controller.go
- controllers/template_controller_test.go
- controllers/templateinstance_controller.go
- controllers/templateinstance_controller_test.go
- internal/argo.go
- internal/git.go
- internal/k8s.go
- internal/param.go
- refactor package name & parameter handling
> [mod] refactor package name & parameter handling

- api/v1/template_types.go
- config/crd/bases/tmax.io_clustertemplates.yaml
- config/crd/bases/tmax.io_templates.yaml
- controllers/templateinstance_controller_test.go
- internal/git.go
- internal/param.go
- Changed paramSpec.ValueType as required field
- Revised parameter value type conversion part
> [feat] Revised type handling of parameter values

- api/v1/template_types.go
- config/crd/bases/tmax.io_clustertemplates.yaml
- config/crd/bases/tmax.io_templates.yaml
rollback paramSpec.ValueType as omitempty
> rollback paramSpec.ValueType as omitempty

- controllers/clustertemplate_controller.go
- controllers/template_controller.go
- controllers/templateinstance_controller.go
- internal/resolver/template_resolver.go
- Set valueType field as deafult string in template parameters
- Removed unnecessary repeated log
> Set default valueType field

- controllers/templateinstance_controller.go
- internal/git.go
- internal/resolver/template_resolver.go
- Delete created objects when template instance has error
- Resolved problem that error Info is converged as "certain object already exists"
> [feat] Delete created objects when template instance has error
